usuarios/applications/home/urls.py
from django.urls import path
from . import views

app_name = 'home_app'

urlpatterns = [
    path('panel/', views.HomePage.as_view(), name='panel'),
    path('mixin/', views.TemplatePruebaMixin.as_view(), name='mixin'),
]

usuarios/applications/users/urls.py
from django.urls import path
from . import views

app_name = 'users_app'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user-register'),
    path('login/', views.LoginUser.as_view(), name='user-login'),
    path('logout/', views.LogoutView.as_view(), name='user-logout'),
    path('update/', views.UpdatePasswordView.as_view(), name='user-update'),
    path('user-verification/<pk>/', views.CodeVerificationView.as_view(), name='user-verification'),
]

usuarios/usuarios/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
]

usuarios/applications/home/models.py
from django.db import models

# Create your models here.

usuarios/applications/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin

from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):

    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otros'),
    )

    username = models.CharField(max_length=10, unique=True)
    email = models.EmailField()
    nombres = models.CharField(max_length=30, blank=True)
    apellidos = models.CharField(max_length=30, blank=True)
    genero = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    codregistro = models.CharField(max_length=6, blank=True)

    is_staff = models.BooleanField(default=False) #Vienen del abstract
    is_active = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = ['email',]

    objects = UserManager()

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return self.nombres + ' ' + self.apellidos

usuarios/applications/home/views.py
import datetime

from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse

from django.views.generic import TemplateView

# Create your views here.

class FechaMixin(object):

    def get_context_data(self, **kwargs):
        context = super(FechaMixin, self).get_context_data(**kwargs)
        context['fecha'] = datetime.datetime.now()
        return context


class HomePage(LoginRequiredMixin, TemplateView):
    template_name = 'home/index.html'
    login_url = reverse_lazy('users_app:user-login')# lo requiere el mixin para cuando el usuario no esté registrado y quiere acceder a alguna url que necesita login



class TemplatePruebaMixin(FechaMixin, TemplateView):
    template_name = "home/mixin.html"

usuarios/applications/users/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

from django.views.generic.edit import FormView
from django.views.generic import View, CreateView

from .form import UserRegisterForm, LoginForm, UpdatePasswordForm, VerificationForm

from .models import User
from .functions import code_generator

# Create your views here.

class UserRegisterView(FormView):
    template_name = 'users/register.html'
    form_class = UserRegisterForm
    success_url = '/'

    def form_valid(self, form):
        # generamos codigo
        codigo = code_generator()

        usuario = User.objects.create_user(
            form.cleaned_data['username'], #con el cleaned data recuperamos el valor de los formularios
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            nombres=form.cleaned_data['nombres'],
            apellidos=form.cleaned_data['apellidos'],
            genero=form.cleaned_data['genero'],
            codregistro=codigo
        )
        #enviar codigo al email
        asunto = 'Confirmación de email'
        mensaje = 'Código de verificación: ' + codigo
        email_remitente = 'dani.aguilera87@gmail.com'

        send_mail(asunto, mensaje, email_remitente, [form.cleaned_data['email'],]) #siempre es un array por si se envia a mas de un usuario
        # una vez confirmado redirigir a pantalla de confirmación.

        return HttpResponseRedirect(
            reverse(
                'users_app:user-verification',
                kwargs={'pk': usuario.id}
            )
        )

class LoginUser(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('home_app:panel')

    def form_valid(self, form):
        user = authenticate(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password'],
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:user-login'
            )
        )

class UpdatePasswordView(LoginRequiredMixin, FormView):
    template_name = 'users/update.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('users_app:user-login')
    login_url = reverse_lazy('users_app:user-login')

    def form_valid(self, form):
        usuario = self.request.user # primero verificar el usuario que esta logueado.
        user = authenticate(
            username=usuario.username,
            password=form.cleaned_data['password1'] #autenticamos el usuario
        )
        if user:
            new_password = form.cleaned_data['password2'] # recuperamos el password nuevo
            usuario.set_password(new_password)
            usuario.save()


        logout(self.request)

        return super(UpdatePasswordView, self).form_valid(form)

class CodeVerificationView(FormView):
    template_name = 'users/verification.html'
    form_class = VerificationForm
    success_url = reverse_lazy('users_app:user-login')

    def get_form_kwargs(self): # enviar nuevos pk a nuestro formulario
        kwargs = super(CodeVerificationView, self). get_form_kwargs()
        kwargs.update({
            'pk': self.kwargs['pk'] #guardamos el pk de la url para poder llamarlo desde el form
        })
        return kwargs

    def form_valid(self, form):

        User.objects.filter(
            id=self.kwargs['pk']
        ).update(
            is_active=True # para poner activo el ID de usuario que recogemos de la url
        )

        return super(CodeVerificationView, self).form_valid(form)

usuarios/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device.width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Panel de usuario</h1>
    <h3>Bienvenido: {{user}}</h3>
    <ul>
        <li><a href="{% url 'users_app:user-logout' %}">Cerrar sesión</a></li>
        <li><a href="{% url 'users_app:user-update' %}">Actualizar datos</a></li>

    </ul>
</body>
</html>

usuarios/templates/home/mixin.html
<h1>Probando mixin</h1>

{{ fecha }}

usuarios/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device.width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Acceder al sistema</h1>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Acceder</button>
    </form>
</body>
</html>

usuarios/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device.width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Registrar nuevo usuario</h1>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Registrar</button>

    </form>

</body>
</html>

usuarios/templates/users/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device.width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Cambiar contraseña: {{ user.get_full_name }}</h1>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Actualizar</button>
    </form>
</body>
</html>

usuarios/templates/users/verification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device.width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Verificación Email</h1>
    <h3>Ingrese el código de verificación</h3>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Confirmar</button>
    </form>

</body>
</html>